; ACOS Change Over Switch – PlatformIO Configuration


[platformio]
default_envs = m5stack-cores3
description = ACOS

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
board_build.esp32s3.psram = enabled
lib_deps =
    ; --- M5 Stack Core ---
    m5stack/M5Unified @ 0.1.17
    ;m5stack/M5CoreS3 @ ^0.0.3

    ; --- IO Expander ---
    https://github.com/nicoverduin/PCA9555.git #v1.0.0

    ; --- CAN MCP2515 ---
    https://github.com/autowp/arduino-mcp2515.git#v1.1.0
   
    
  
 

; Build-Optimierungen
build_flags = 
	-O2
	-Wall
	-DAPP_VERSION=\"dev\"
monitor_filters = colorize, esp32_exception_decoder
debug_tool = esp-prog
debug_init_break = tbreak setup



